blank_issues_enabled: false
contact_links:
  - name: ❓ Domanda generica
    url: https://github.com/Automercatorum/Web/discussions
    about: Per domande sull'utilizzo, preferisci la discussione qui.
